//! Nationality, Religion, and Political Affiliation (NRP) lexicons
//!
//! Embedded lexicons for `&[&str]` matching via Aho-Corasick. Used to detect
//! GDPR Article 9 special-category data (racial origin, religious belief,
//! political opinion) without requiring an ML model.
//!
//! ## Coverage
//!
//! - `NATIONALITIES`: ~200 demonyms (adjective forms of country/people names).
//!   Source: ISO 3166-1 demonyms, ethnic group names commonly used in
//!   English-language free text.
//! - `RELIGIONS`: ~50 named religions and denominations.
//! - `POLITICAL_AFFILIATIONS`: ~30 political parties and ideological labels.
//!
//! ## Matching Semantics
//!
//! All matches are case-insensitive and **word-bounded** by the caller
//! (see `personal/detection/nrp.rs`). Aho-Corasick reports raw positions;
//! callers reject matches that lack alphanumeric boundaries on either side
//! to prevent e.g. `"Catholic"` matching inside `"Catholicism"`.
//!
//! ## Maintenance
//!
//! Lists are intentionally additive — removing an entry is a soft breaking
//! change for downstream PII redaction. New entries should be vetted for
//! ambiguity (e.g. avoid generic words that also have non-NRP meanings).

/// Nationalities and ethnic-group adjectives.
///
/// Roughly one entry per recognised country plus major ethnic groups.
/// Entries are demonyms (e.g. "American", not "America").
pub(crate) const NATIONALITIES: &[&str] = &[
    // Africa
    "Algerian",
    "Angolan",
    "Beninese",
    "Botswanan",
    "Burkinabé",
    "Burundian",
    "Cameroonian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Comorian",
    "Congolese",
    "Djiboutian",
    "Egyptian",
    "Equatorial Guinean",
    "Eritrean",
    "Ethiopian",
    "Gabonese",
    "Gambian",
    "Ghanaian",
    "Guinean",
    "Bissau-Guinean",
    "Ivorian",
    "Kenyan",
    "Lesothan",
    "Liberian",
    "Libyan",
    "Malagasy",
    "Malawian",
    "Malian",
    "Mauritanian",
    "Mauritian",
    "Moroccan",
    "Mozambican",
    "Namibian",
    "Nigerien",
    "Nigerian",
    "Rwandan",
    "Senegalese",
    "Seychellois",
    "Sierra Leonean",
    "Somali",
    "South African",
    "Sudanese",
    "Tanzanian",
    "Togolese",
    "Tunisian",
    "Ugandan",
    "Zambian",
    "Zimbabwean",
    // Americas
    "American",
    "Antiguan",
    "Argentine",
    "Argentinian",
    "Bahamian",
    "Barbadian",
    "Belizean",
    "Bolivian",
    "Brazilian",
    "Canadian",
    "Chilean",
    "Colombian",
    "Costa Rican",
    "Cuban",
    "Dominican",
    "Ecuadorian",
    "Salvadoran",
    "Grenadian",
    "Guatemalan",
    "Guyanese",
    "Haitian",
    "Honduran",
    "Jamaican",
    "Mexican",
    "Nicaraguan",
    "Panamanian",
    "Paraguayan",
    "Peruvian",
    "Puerto Rican",
    "Saint Lucian",
    "Surinamese",
    "Trinidadian",
    "Uruguayan",
    "Venezuelan",
    // Asia
    "Afghan",
    "Armenian",
    "Azerbaijani",
    "Bahraini",
    "Bangladeshi",
    "Bhutanese",
    "Bruneian",
    "Cambodian",
    "Chinese",
    "Cypriot",
    "Emirati",
    "Filipino",
    "Georgian",
    "Indian",
    "Indonesian",
    "Iranian",
    "Persian",
    "Iraqi",
    "Israeli",
    "Japanese",
    "Jordanian",
    "Kazakh",
    "Kuwaiti",
    "Kyrgyz",
    "Laotian",
    "Lebanese",
    "Malaysian",
    "Maldivian",
    "Mongolian",
    "Burmese",
    "Myanmar",
    "Nepali",
    "Nepalese",
    "North Korean",
    "Omani",
    "Pakistani",
    "Palestinian",
    "Qatari",
    "Saudi",
    "Singaporean",
    "South Korean",
    "Korean",
    "Sri Lankan",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Thai",
    "Timorese",
    "Turkish",
    "Turkmen",
    "Uzbek",
    "Vietnamese",
    "Yemeni",
    // Europe
    "Albanian",
    "Andorran",
    "Austrian",
    "Belarusian",
    "Belgian",
    "Bosnian",
    "Herzegovinian",
    "Bulgarian",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Hungarian",
    "Icelandic",
    "Irish",
    "Italian",
    "Kosovar",
    "Latvian",
    "Liechtensteiner",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Maltese",
    "Moldovan",
    "Monégasque",
    "Montenegrin",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Sammarinese",
    "Scottish",
    "Serbian",
    "Slovak",
    "Slovakian",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Swiss",
    "Ukrainian",
    "British",
    "Welsh",
    // Oceania
    "Australian",
    "Fijian",
    "I-Kiribati",
    "Marshallese",
    "Micronesian",
    "Nauruan",
    "New Zealander",
    "Kiwi",
    "Palauan",
    "Papua New Guinean",
    "Samoan",
    "Solomon Islander",
    "Tongan",
    "Tuvaluan",
    "Ni-Vanuatu",
    // Ethnic / pan-regional descriptors commonly used in English text
    "Hispanic",
    "Latino",
    "Latina",
    "Latinx",
    "Asian",
    "African",
    "European",
    "Middle Eastern",
    "Caucasian",
    "African American",
    "Afro-Caribbean",
    "Native American",
    "Indigenous",
    "Aboriginal",
    "Polynesian",
    "Melanesian",
    "Kurdish",
    "Romani",
    "Roma",
    "Sami",
    "Inuit",
    "Berber",
    "Tibetan",
    "Uyghur",
    "Hmong",
];

/// Religious affiliations and denominations.
///
/// Includes major world religions, well-known denominations, and a few
/// non-religious affiliations (atheist, agnostic) since they fall under the
/// same GDPR Art. 9 category as religious belief.
pub(crate) const RELIGIONS: &[&str] = &[
    "Christian",
    "Catholic",
    "Roman Catholic",
    "Protestant",
    "Orthodox",
    "Eastern Orthodox",
    "Anglican",
    "Episcopalian",
    "Baptist",
    "Methodist",
    "Lutheran",
    "Presbyterian",
    "Pentecostal",
    "Evangelical",
    "Mormon",
    "Latter-day Saint",
    "LDS",
    "Jehovah's Witness",
    "Quaker",
    "Mennonite",
    "Amish",
    "Coptic",
    "Maronite",
    "Muslim",
    "Sunni",
    "Shia",
    "Shiite",
    "Sufi",
    "Ahmadiyya",
    "Ismaili",
    "Alawite",
    "Druze",
    "Jewish",
    "Orthodox Jewish",
    "Hasidic",
    "Reform Jewish",
    "Conservative Jewish",
    "Hindu",
    "Buddhist",
    "Theravada",
    "Mahayana",
    "Tibetan Buddhist",
    "Zen",
    "Sikh",
    "Jain",
    "Bahá'í",
    "Bahai",
    "Shinto",
    "Taoist",
    "Daoist",
    "Confucian",
    "Zoroastrian",
    "Rastafarian",
    "Wiccan",
    "Pagan",
    "Neopagan",
    "Atheist",
    "Agnostic",
    "Secular",
    "Humanist",
];

/// Political affiliations — major parties and ideological labels.
///
/// Mix of US/UK/EU parties + cross-national ideological labels.
pub(crate) const POLITICAL_AFFILIATIONS: &[&str] = &[
    // US
    "Democrat",
    "Democratic",
    "Republican",
    "GOP",
    "Libertarian",
    "Green Party",
    // UK
    "Labour",
    "Tory",
    "Conservative",
    "Lib Dem",
    "Liberal Democrat",
    "SNP",
    "Sinn Féin",
    "Plaid Cymru",
    // EU / cross-national
    "Social Democrat",
    "Christian Democrat",
    "Communist",
    "Socialist",
    "Marxist",
    "Leninist",
    "Trotskyist",
    "Anarchist",
    "Fascist",
    "Neo-fascist",
    "Nationalist",
    "Populist",
    // Ideological labels
    "Liberal",
    "Progressive",
    "Centrist",
    "Far-left",
    "Far-right",
    "Alt-right",
    "Leftist",
    "Right-wing",
    "Left-wing",
];
