//! Gazetteer lexicons for free-text named-location detection
//!
// arch-check: allow file-length — this file is ~2,500 LOC of pure data
// (string-literal arrays for COUNTRIES, CITIES, AMBIGUOUS_PLACE_NAMES).
// Splitting the data would harm discoverability without any code-quality
// benefit; the file contains essentially no executable code, only static
// constants.
//
//! Curated string arrays of country and major-city names used by
//! Aho-Corasick scanning in `primitives/identifiers/location/detection/named.rs`.
//!
//! ## Coverage
//!
//! - [`COUNTRIES`] — ISO 3166-1 country names plus common short forms
//!   ("United States", "USA", "America", "UK", "Britain"). ~280 entries.
//! - [`CITIES`] — Major world cities, drawn from GeoNames `cities5000`
//!   (cities with population > 5,000) and filtered to roughly the top
//!   1,500 by population plus national/regional capitals for global
//!   coverage. Diacritic and ASCII transliterations are both included
//!   for cities whose canonical name contains non-ASCII characters
//!   (e.g. "São Paulo" + "Sao Paulo", "Zürich" + "Zurich").
//! - [`AMBIGUOUS_PLACE_NAMES`] — Place names that are also common English
//!   words. Matches against these entries are *downgraded* to
//!   `DetectionConfidence::Low` unless a location-context keyword is
//!   present. The list is intentionally short and conservative so the
//!   caller still sees the match in audit trails.
//!
//! ## Matching Semantics
//!
//! - Case-insensitive (handled by `aho-corasick` `ascii_case_insensitive`).
//! - Word-bounded by the caller — prevents `"Paris"` matching inside
//!   `"ParisHilton"`.
//! - Multi-word entries handled by Aho-Corasick `LeftmostLongest` —
//!   `"New York"` matches as one token, not `"York"` alone.
//!
//! ## Maintenance
//!
//! Entries are stored in Title Case (the canonical form). Removing a
//! city or country is a soft breaking change for downstream redaction
//! — prefer additions over removals. New entries should be vetted for
//! ambiguity (common English words → add to `AMBIGUOUS_PLACE_NAMES`
//! instead of dropping the entry).
//!
//! ## Attribution
//!
//! City names are derived from the GeoNames geographical database
//! (<https://www.geonames.org/>), available under the Creative Commons
//! Attribution 4.0 License (CC BY 4.0). The data used here is a curated
//! subset; no GeoNames identifiers or coordinates are retained.

// ============================================================================
// Countries (ISO 3166-1 + common short forms)
// ============================================================================

/// Country names — ISO 3166-1 short names plus common alternate forms.
///
/// Entries are stored in Title Case; matching is case-insensitive.
/// Includes both formal names ("United States of America") and common
/// short forms ("United States", "USA", "America") because free text
/// uses all variants.
pub(crate) const COUNTRIES: &[&str] = &[
    // A
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    // B
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    // C
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Czech Republic",
    "Côte d'Ivoire",
    "Cote d'Ivoire",
    "Ivory Coast",
    // D
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    // E
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Swaziland",
    "Ethiopia",
    // F
    "Fiji",
    "Finland",
    "France",
    // G
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    // H
    "Haiti",
    "Honduras",
    "Hungary",
    // I
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    // J
    "Jamaica",
    "Japan",
    "Jordan",
    // K
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    // L
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    // M
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Burma",
    // N
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Holland",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Macedonia",
    "Norway",
    // O
    "Oman",
    // P
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    // Q
    "Qatar",
    // R
    "Romania",
    "Russia",
    "Russian Federation",
    "Rwanda",
    // S
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "São Tomé and Príncipe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    // T
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "East Timor",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Türkiye",
    "Turkmenistan",
    "Tuvalu",
    // U
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "UAE",
    "United Kingdom",
    "Great Britain",
    "Britain",
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
    "UK",
    "United States",
    "United States of America",
    "USA",
    "America",
    "Uruguay",
    "Uzbekistan",
    // V
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    // W (no UN members starting with W)
    // Y
    "Yemen",
    // Z
    "Zambia",
    "Zimbabwe",
];

// ============================================================================
// Major Cities
// ============================================================================

/// Major world cities — roughly the top 1,500 by population plus national
/// and regional capitals for global coverage.
///
/// Entries with non-ASCII canonical names are duplicated as ASCII
/// transliterations so the Aho-Corasick `ascii_case_insensitive` matcher
/// catches both forms (it does not fold diacritics).
///
/// Filtered to exclude entries < 3 characters (avoids noise like "Ai",
/// "Oz"). City-name collisions with common English words are kept in the
/// gazetteer but are downgraded to `Low` confidence via
/// [`AMBIGUOUS_PLACE_NAMES`] when no location-context keyword is nearby.
pub(crate) const CITIES: &[&str] = &[
    // ---- North America (US) ----
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Kansas City",
    "Mesa",
    "Atlanta",
    "Omaha",
    "Colorado Springs",
    "Raleigh",
    "Miami",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Bakersfield",
    "Wichita",
    "Arlington",
    "Aurora",
    "Tampa",
    "New Orleans",
    "Cleveland",
    "Honolulu",
    "Anaheim",
    "Lexington",
    "Stockton",
    "Corpus Christi",
    "Henderson",
    "Riverside",
    "Newark",
    "Saint Paul",
    "Santa Ana",
    "Cincinnati",
    "Irvine",
    "Orlando",
    "Pittsburgh",
    "St. Louis",
    "St Louis",
    "Greensboro",
    "Jersey City",
    "Anchorage",
    "Lincoln",
    "Plano",
    "Durham",
    "Buffalo",
    "Chandler",
    "Chula Vista",
    "Toledo",
    "Madison",
    "Gilbert",
    "Reno",
    "Fort Wayne",
    "North Las Vegas",
    "St. Petersburg",
    "St Petersburg",
    "Lubbock",
    "Irving",
    "Laredo",
    "Winston-Salem",
    "Chesapeake",
    "Glendale",
    "Garland",
    "Scottsdale",
    "Boise",
    "Norfolk",
    "Spokane",
    "Fremont",
    "Richmond",
    "Santa Clarita",
    "San Bernardino",
    "Baton Rouge",
    "Hialeah",
    "Tacoma",
    "Modesto",
    "Port St. Lucie",
    "Huntsville",
    "Des Moines",
    "Moreno Valley",
    "Fontana",
    "Frisco",
    "Rochester",
    "Yonkers",
    "Fayetteville",
    "Worcester",
    "Columbus",
    "Cape Coral",
    "McKinney",
    "Little Rock",
    "Oxnard",
    "Amarillo",
    "Augusta",
    "Salt Lake City",
    "Montgomery",
    "Birmingham",
    "Grand Rapids",
    "Tallahassee",
    "Huntington Beach",
    "Overland Park",
    "Knoxville",
    "Providence",
    "Akron",
    "Brownsville",
    "Mobile",
    "Newport News",
    "Tempe",
    "Shreveport",
    "Chattanooga",
    "Fort Lauderdale",
    "Aurora",
    "Eugene",
    "Cary",
    "Salem",
    "Ontario",
    "Santa Rosa",
    "Rancho Cucamonga",
    "Oceanside",
    "Lancaster",
    "Garden Grove",
    "Pembroke Pines",
    "Springfield",
    "Sioux Falls",
    "Peoria",
    "Elk Grove",
    "Corona",
    "Hayward",
    "Hartford",
    "Salinas",
    "Fort Collins",
    "Lakewood",
    "Pomona",
    "Palmdale",
    "Sunnyvale",
    "Escondido",
    "Naperville",
    "Joliet",
    "Killeen",
    "Bellevue",
    "Pasadena",
    "Syracuse",
    "Dayton",
    "Savannah",
    "Roseville",
    "Macon",
    "Mesquite",
    "Bridgeport",
    "Denton",
    "Olathe",
    "Surprise",
    "Thornton",
    "McAllen",
    "Waco",
    "Carrollton",
    "Midland",
    "Charleston",
    "Warren",
    "Hampton",
    "Gainesville",
    "Visalia",
    "Coral Springs",
    "Columbia",
    "Cedar Rapids",
    "Sterling Heights",
    "New Haven",
    "Stamford",
    "Concord",
    "Kent",
    "Santa Clara",
    "Elizabeth",
    "Round Rock",
    "Thousand Oaks",
    "Lafayette",
    "Athens",
    "Topeka",
    "Simi Valley",
    "Fargo",
    "Norman",
    "Columbia",
    "Abilene",
    "Wilmington",
    "Hollywood",
    "Berkeley",
    "Allentown",
    "Beaumont",
    "Murfreesboro",
    "Provo",
    "El Monte",
    "Independence",
    "Lansing",
    "Ann Arbor",
    "Rochester",
    "Flint",
    "Cambridge",
    "Trenton",
    "Erie",
    "Lowell",
    "Manchester",
    "Spokane Valley",
    "Sandy Springs",
    "Roanoke",
    "Pearland",
    "College Station",
    "Clearwater",
    "West Valley City",
    "Gresham",
    "Fairfield",
    "Billings",
    "Lewisville",
    "Inglewood",
    "Richardson",
    "Murrieta",
    "Beaverton",
    "West Jordan",
    "Wichita Falls",
    "Costa Mesa",
    "Pueblo",
    "Antioch",
    "Downey",
    "South Bend",
    "Burbank",
    "El Cajon",
    "Vallejo",
    "Carlsbad",
    "Pompano Beach",
    "Fairfield",
    "Norwalk",
    "Daly City",
    "Temecula",
    "Greeley",
    "Renton",
    "Boulder",
    "Concord",
    "Tyler",
    "Edison",
    "Allen",
    "Las Cruces",
    "Sandy",
    "Quincy",
    "Sparks",
    "Hartford",
    "Springfield",
    "Bellingham",
    "Cary",
    // ---- North America (Canada) ----
    "Toronto",
    "Montreal",
    "Montréal",
    "Calgary",
    "Ottawa",
    "Edmonton",
    "Mississauga",
    "Winnipeg",
    "Vancouver",
    "Brampton",
    "Hamilton",
    "Quebec City",
    "Québec",
    "Surrey",
    "Laval",
    "Halifax",
    "London",
    "Markham",
    "Vaughan",
    "Gatineau",
    "Saskatoon",
    "Longueuil",
    "Burnaby",
    "Regina",
    "Richmond",
    "Oakville",
    "Burlington",
    "Greater Sudbury",
    "Sherbrooke",
    "Oshawa",
    "Saguenay",
    "Lévis",
    "Barrie",
    "Abbotsford",
    "St. Catharines",
    "Trois-Rivières",
    "Cambridge",
    "Coquitlam",
    "Kingston",
    "Whitby",
    "Guelph",
    "Kelowna",
    "Saanich",
    "Ajax",
    "Thunder Bay",
    "Terrebonne",
    "St. John's",
    "Langley",
    "Chatham-Kent",
    "Delta",
    "Waterloo",
    "Cape Breton",
    "Brantford",
    "Strathcona County",
    "Saint-Jérôme",
    "Red Deer",
    "Pickering",
    "Kamloops",
    "Clarington",
    "North Vancouver",
    "Milton",
    "Niagara Falls",
    "Lethbridge",
    "Repentigny",
    "Moncton",
    "Brossard",
    "Peterborough",
    "Saint John",
    "Maple Ridge",
    "Drummondville",
    "Sault Ste. Marie",
    "Kawartha Lakes",
    "Prince George",
    // ---- North America (Mexico) ----
    "Mexico City",
    "Iztapalapa",
    "Ecatepec",
    "Guadalajara",
    "Puebla",
    "Tijuana",
    "Ciudad Juárez",
    "León",
    "Zapopan",
    "Monterrey",
    "Nezahualcóyotl",
    "Chihuahua",
    "Naucalpan",
    "Mérida",
    "San Luis Potosí",
    "Aguascalientes",
    "Hermosillo",
    "Saltillo",
    "Mexicali",
    "Culiacán",
    "Acapulco",
    "Querétaro",
    "Morelia",
    "Cuernavaca",
    "Oaxaca",
    "Veracruz",
    "Cancún",
    "Cancun",
    "Tampico",
    // ---- Central America & Caribbean ----
    "Guatemala City",
    "San Salvador",
    "Tegucigalpa",
    "Managua",
    "San José",
    "San Jose",
    "Panama City",
    "Belmopan",
    "Havana",
    "Santo Domingo",
    "Port-au-Prince",
    "Kingston",
    "San Juan",
    "Nassau",
    "Bridgetown",
    "Port of Spain",
    // ---- South America ----
    "São Paulo",
    "Sao Paulo",
    "Rio de Janeiro",
    "Salvador",
    "Brasília",
    "Brasilia",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Belém",
    "Belem",
    "Goiânia",
    "Goiania",
    "Guarulhos",
    "Campinas",
    "São Luís",
    "Sao Luis",
    "Buenos Aires",
    "Córdoba",
    "Cordoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Mar del Plata",
    "San Miguel de Tucumán",
    "Santiago",
    "Valparaíso",
    "Valparaiso",
    "Concepción",
    "Concepcion",
    "Antofagasta",
    "Lima",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Bogotá",
    "Bogota",
    "Medellín",
    "Medellin",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Quito",
    "Guayaquil",
    "Cuenca",
    "La Paz",
    "Santa Cruz",
    "Cochabamba",
    "Sucre",
    "Asunción",
    "Asuncion",
    "Montevideo",
    "Georgetown",
    "Paramaribo",
    "Cayenne",
    // ---- Europe (Western) ----
    "London",
    "Birmingham",
    "Glasgow",
    "Liverpool",
    "Leeds",
    "Sheffield",
    "Edinburgh",
    "Bristol",
    "Cardiff",
    "Belfast",
    "Manchester",
    "Newcastle",
    "Nottingham",
    "Coventry",
    "Leicester",
    "Bradford",
    "Plymouth",
    "Stoke-on-Trent",
    "Wolverhampton",
    "Derby",
    "Southampton",
    "Portsmouth",
    "Reading",
    "Brighton",
    "Aberdeen",
    "Hull",
    "York",
    "Oxford",
    "Cambridge",
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint-Étienne",
    "Saint-Etienne",
    "Toulon",
    "Angers",
    "Grenoble",
    "Dijon",
    "Nîmes",
    "Nimes",
    "Aix-en-Provence",
    "Brest",
    "Le Mans",
    "Amiens",
    "Tours",
    "Limoges",
    "Clermont-Ferrand",
    "Villeurbanne",
    "Besançon",
    "Besancon",
    "Orléans",
    "Orleans",
    "Metz",
    "Rouen",
    "Mulhouse",
    "Caen",
    "Nancy",
    "Berlin",
    "Hamburg",
    "Munich",
    "München",
    "Cologne",
    "Köln",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dusseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Bremen",
    "Dresden",
    "Hannover",
    "Nuremberg",
    "Nürnberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Munster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
    "Halle",
    "Magdeburg",
    "Freiburg",
    "Krefeld",
    "Lübeck",
    "Lubeck",
    "Oberhausen",
    "Erfurt",
    "Mainz",
    "Rostock",
    "Kassel",
    "Hagen",
    "Potsdam",
    "Saarbrücken",
    "Saarbrucken",
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Malaga",
    "Murcia",
    "Palma",
    "Las Palmas",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "Gijon",
    "Granada",
    "A Coruña",
    "La Coruna",
    "Vitoria-Gasteiz",
    "Elche",
    "Oviedo",
    "Santa Cruz de Tenerife",
    "Badalona",
    "Cartagena",
    "Terrassa",
    "Jerez",
    "Sabadell",
    "Móstoles",
    "Mostoles",
    "Alcalá de Henares",
    "Pamplona",
    "Fuenlabrada",
    "Almería",
    "Almeria",
    "Leganés",
    "San Sebastián",
    "San Sebastian",
    "Burgos",
    "Santander",
    "Castellón",
    "Castellon",
    "Albacete",
    "Getafe",
    "Alcorcón",
    "Logroño",
    "Logrono",
    "Badajoz",
    "Salamanca",
    "Huelva",
    "Marbella",
    "Tarragona",
    "Rome",
    "Roma",
    "Milan",
    "Milano",
    "Naples",
    "Napoli",
    "Turin",
    "Torino",
    "Palermo",
    "Genoa",
    "Genova",
    "Bologna",
    "Florence",
    "Firenze",
    "Bari",
    "Catania",
    "Venice",
    "Venezia",
    "Verona",
    "Messina",
    "Padua",
    "Padova",
    "Trieste",
    "Brescia",
    "Parma",
    "Taranto",
    "Prato",
    "Modena",
    "Reggio Calabria",
    "Reggio Emilia",
    "Perugia",
    "Livorno",
    "Ravenna",
    "Cagliari",
    "Foggia",
    "Rimini",
    "Salerno",
    "Ferrara",
    "Sassari",
    "Latina",
    "Giugliano",
    "Monza",
    "Lisbon",
    "Lisboa",
    "Porto",
    "Vila Nova de Gaia",
    "Amadora",
    "Braga",
    "Funchal",
    "Coimbra",
    "Setúbal",
    "Setubal",
    "Almada",
    "Aveiro",
    "Faro",
    "Évora",
    "Evora",
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Den Haag",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen",
    "Enschede",
    "Haarlem",
    "Arnhem",
    "Zaanstad",
    "Apeldoorn",
    "Amersfoort",
    "Hoofddorp",
    "Maastricht",
    "Leiden",
    "Dordrecht",
    "Zwolle",
    "Delft",
    "Brussels",
    "Bruxelles",
    "Antwerp",
    "Antwerpen",
    "Ghent",
    "Gent",
    "Charleroi",
    "Liège",
    "Liege",
    "Bruges",
    "Brugge",
    "Namur",
    "Leuven",
    "Mons",
    "Aalst",
    "Mechelen",
    "Hasselt",
    "Vienna",
    "Wien",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "Villach",
    "Wels",
    "Sankt Pölten",
    "Dornbirn",
    "Zurich",
    "Zürich",
    "Geneva",
    "Genève",
    "Basel",
    "Bern",
    "Lausanne",
    "Winterthur",
    "Lucerne",
    "Luzern",
    "St. Gallen",
    "Lugano",
    "Biel",
    "Thun",
    "Köniz",
    "La Chaux-de-Fonds",
    "Schaffhausen",
    "Fribourg",
    "Chur",
    "Vernier",
    "Sion",
    "Luxembourg City",
    "Esch-sur-Alzette",
    "Dudelange",
    "Schifflange",
    "Bettembourg",
    // ---- Europe (Nordic) ----
    "Stockholm",
    "Gothenburg",
    "Göteborg",
    "Malmö",
    "Malmo",
    "Uppsala",
    "Västerås",
    "Vasteras",
    "Örebro",
    "Orebro",
    "Linköping",
    "Linkoping",
    "Helsingborg",
    "Jönköping",
    "Jonkoping",
    "Norrköping",
    "Norrkoping",
    "Lund",
    "Umeå",
    "Umea",
    "Gävle",
    "Gavle",
    "Borås",
    "Boras",
    "Södertälje",
    "Eskilstuna",
    "Halmstad",
    "Växjö",
    "Vaxjo",
    "Karlstad",
    "Sundsvall",
    "Östersund",
    "Trollhättan",
    "Luleå",
    "Lulea",
    "Kalmar",
    "Kristianstad",
    "Falun",
    "Skellefteå",
    "Karlskrona",
    "Visby",
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
    "Drammen",
    "Fredrikstad",
    "Kristiansand",
    "Tromsø",
    "Tromso",
    "Sandnes",
    "Sarpsborg",
    "Bodø",
    "Bodo",
    "Ålesund",
    "Alesund",
    "Sandefjord",
    "Hamar",
    "Larvik",
    "Halden",
    "Lillehammer",
    "Molde",
    "Copenhagen",
    "København",
    "Aarhus",
    "Århus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Roskilde",
    "Herning",
    "Helsingør",
    "Helsingor",
    "Silkeborg",
    "Næstved",
    "Naestved",
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyväskylä",
    "Jyvaskyla",
    "Lahti",
    "Kuopio",
    "Pori",
    "Joensuu",
    "Lappeenranta",
    "Hämeenlinna",
    "Hameenlinna",
    "Vaasa",
    "Seinäjoki",
    "Seinajoki",
    "Rovaniemi",
    "Mikkeli",
    "Kotka",
    "Salo",
    "Porvoo",
    "Reykjavík",
    "Reykjavik",
    "Kópavogur",
    "Hafnarfjörður",
    "Akureyri",
    "Reykjanesbær",
    // ---- Europe (Eastern) ----
    "Warsaw",
    "Warszawa",
    "Kraków",
    "Krakow",
    "Łódź",
    "Lodz",
    "Wrocław",
    "Wroclaw",
    "Poznań",
    "Poznan",
    "Gdańsk",
    "Gdansk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Białystok",
    "Bialystok",
    "Katowice",
    "Gdynia",
    "Częstochowa",
    "Czestochowa",
    "Radom",
    "Sosnowiec",
    "Toruń",
    "Torun",
    "Kielce",
    "Rzeszów",
    "Rzeszow",
    "Gliwice",
    "Olsztyn",
    "Zabrze",
    "Bielsko-Biała",
    "Prague",
    "Praha",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Pilsen",
    "Liberec",
    "Olomouc",
    "České Budějovice",
    "Hradec Králové",
    "Pardubice",
    "Zlín",
    "Zlin",
    "Havířov",
    "Havirov",
    "Bratislava",
    "Košice",
    "Kosice",
    "Prešov",
    "Presov",
    "Žilina",
    "Zilina",
    "Banská Bystrica",
    "Nitra",
    "Trnava",
    "Trenčín",
    "Trencin",
    "Budapest",
    "Debrecen",
    "Szeged",
    "Miskolc",
    "Pécs",
    "Pecs",
    "Győr",
    "Gyor",
    "Nyíregyháza",
    "Nyiregyhaza",
    "Kecskemét",
    "Kecskemet",
    "Székesfehérvár",
    "Szombathely",
    "Sopron",
    "Eger",
    "Bucharest",
    "București",
    "Cluj-Napoca",
    "Timișoara",
    "Timisoara",
    "Iași",
    "Iasi",
    "Constanța",
    "Constanta",
    "Craiova",
    "Brașov",
    "Brasov",
    "Galați",
    "Galati",
    "Ploiești",
    "Ploiesti",
    "Oradea",
    "Brăila",
    "Braila",
    "Arad",
    "Pitești",
    "Pitesti",
    "Sibiu",
    "Sofia",
    "София",
    "Plovdiv",
    "Varna",
    "Burgas",
    "Ruse",
    "Stara Zagora",
    "Pleven",
    "Sliven",
    "Dobrich",
    "Shumen",
    "Pernik",
    "Yambol",
    "Athens",
    "Αθήνα",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Ioannina",
    "Chania",
    "Chalcis",
    "Kalamata",
    "Kavala",
    "Serres",
    "Komotini",
    "Belgrade",
    "Beograd",
    "Novi Sad",
    "Niš",
    "Nis",
    "Kragujevac",
    "Subotica",
    "Zrenjanin",
    "Pančevo",
    "Pancevo",
    "Čačak",
    "Cacak",
    "Zagreb",
    "Split",
    "Rijeka",
    "Osijek",
    "Zadar",
    "Pula",
    "Slavonski Brod",
    "Karlovac",
    "Varaždin",
    "Šibenik",
    "Sibenik",
    "Sisak",
    "Dubrovnik",
    "Ljubljana",
    "Maribor",
    "Celje",
    "Kranj",
    "Velenje",
    "Koper",
    "Sarajevo",
    "Banja Luka",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Bijeljina",
    "Skopje",
    "Bitola",
    "Kumanovo",
    "Prilep",
    "Tetovo",
    "Tirana",
    "Tiranë",
    "Durrës",
    "Vlorë",
    "Vlore",
    "Shkodër",
    "Shkoder",
    "Elbasan",
    "Korçë",
    "Korce",
    "Podgorica",
    "Nikšić",
    "Pristina",
    "Prishtinë",
    "Prizren",
    "Peja",
    "Mitrovica",
    "Gjakova",
    "Vilnius",
    "Kaunas",
    "Klaipėda",
    "Klaipeda",
    "Šiauliai",
    "Siauliai",
    "Panevėžys",
    "Panevezys",
    "Riga",
    "Daugavpils",
    "Liepāja",
    "Liepaja",
    "Jelgava",
    "Jūrmala",
    "Jurmala",
    "Ventspils",
    "Tallinn",
    "Tartu",
    "Narva",
    "Pärnu",
    "Parnu",
    "Kohtla-Järve",
    "Moscow",
    "Москва",
    "Saint Petersburg",
    "Sankt-Peterburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Nizhny Novgorod",
    "Chelyabinsk",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Voronezh",
    "Perm",
    "Volgograd",
    "Krasnodar",
    "Saratov",
    "Tyumen",
    "Tolyatti",
    "Izhevsk",
    "Barnaul",
    "Ulyanovsk",
    "Irkutsk",
    "Khabarovsk",
    "Yaroslavl",
    "Vladivostok",
    "Makhachkala",
    "Tomsk",
    "Orenburg",
    "Kemerovo",
    "Novokuznetsk",
    "Ryazan",
    "Astrakhan",
    "Naberezhnye Chelny",
    "Penza",
    "Lipetsk",
    "Tula",
    "Kirov",
    "Cheboksary",
    "Kaliningrad",
    "Sochi",
    "Bryansk",
    "Magnitogorsk",
    "Ivanovo",
    "Tver",
    "Belgorod",
    "Stavropol",
    "Nizhny Tagil",
    "Kursk",
    "Ulan-Ude",
    "Arkhangelsk",
    "Kaluga",
    "Smolensk",
    "Kyiv",
    "Kiev",
    "Kharkiv",
    "Kharkov",
    "Odesa",
    "Odessa",
    "Dnipro",
    "Donetsk",
    "Lviv",
    "Zaporizhzhia",
    "Kryvyi Rih",
    "Mykolaiv",
    "Mariupol",
    "Luhansk",
    "Vinnytsia",
    "Simferopol",
    "Kherson",
    "Poltava",
    "Chernihiv",
    "Cherkasy",
    "Sumy",
    "Zhytomyr",
    "Khmelnytskyi",
    "Chernivtsi",
    "Rivne",
    "Kamianske",
    "Kropyvnytskyi",
    "Ternopil",
    "Lutsk",
    "Bila Tserkva",
    "Kremenchuk",
    "Ivano-Frankivsk",
    "Minsk",
    "Gomel",
    "Mogilev",
    "Vitebsk",
    "Grodno",
    "Brest",
    "Babruysk",
    "Baranavichy",
    "Borisov",
    "Pinsk",
    "Chișinău",
    "Chisinau",
    "Tiraspol",
    "Bălți",
    "Balti",
    "Bender",
    "Cahul",
    // ---- Middle East & North Africa ----
    "Istanbul",
    "Ankara",
    "İzmir",
    "Izmir",
    "Bursa",
    "Adana",
    "Gaziantep",
    "Konya",
    "Antalya",
    "Kayseri",
    "Mersin",
    "Eskişehir",
    "Eskisehir",
    "Diyarbakır",
    "Diyarbakir",
    "Samsun",
    "Denizli",
    "Şanlıurfa",
    "Adapazarı",
    "Malatya",
    "Kahramanmaraş",
    "Erzurum",
    "Van",
    "Batman",
    "Elazığ",
    "İçel",
    "Sivas",
    "Manisa",
    "Tarsus",
    "Trabzon",
    "Çorum",
    "Çanakkale",
    "Tehran",
    "Mashhad",
    "Isfahan",
    "Karaj",
    "Shiraz",
    "Tabriz",
    "Qom",
    "Ahvaz",
    "Kermanshah",
    "Urmia",
    "Rasht",
    "Zahedan",
    "Hamadan",
    "Kerman",
    "Yazd",
    "Ardabil",
    "Bandar Abbas",
    "Arak",
    "Qazvin",
    "Sanandaj",
    "Baghdad",
    "Basra",
    "Mosul",
    "Erbil",
    "Sulaymaniyah",
    "Kirkuk",
    "Najaf",
    "Karbala",
    "Nasiriyah",
    "Amarah",
    "Diwaniyah",
    "Hillah",
    "Damascus",
    "Aleppo",
    "Homs",
    "Latakia",
    "Hama",
    "Raqqa",
    "Deir ez-Zor",
    "Hasaka",
    "Qamishli",
    "Beirut",
    "Tripoli",
    "Sidon",
    "Tyre",
    "Zahle",
    "Jounieh",
    "Amman",
    "Zarqa",
    "Irbid",
    "Russeifa",
    "Aqaba",
    "Madaba",
    "Tel Aviv",
    "Jerusalem",
    "Haifa",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Netanya",
    "Beer Sheva",
    "Holon",
    "Bnei Brak",
    "Ramat Gan",
    "Eilat",
    "Nazareth",
    "Ramallah",
    "Gaza",
    "Hebron",
    "Nablus",
    "Bethlehem",
    "Jericho",
    "Khan Yunis",
    "Rafah",
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Tabuk",
    "Buraidah",
    "Khobar",
    "Khamis Mushait",
    "Hofuf",
    "Taif",
    "Qatif",
    "Yanbu",
    "Hail",
    "Najran",
    "Jubail",
    "Abha",
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Al Ain",
    "Ajman",
    "Ras al-Khaimah",
    "Fujairah",
    "Umm al-Quwain",
    "Doha",
    "Al Wakrah",
    "Al Khor",
    "Al Rayyan",
    "Manama",
    "Muharraq",
    "Riffa",
    "Hamad Town",
    "Kuwait City",
    "Hawalli",
    "Salmiya",
    "Jahra",
    "Farwaniyah",
    "Muscat",
    "Salalah",
    "Sohar",
    "Nizwa",
    "Sur",
    "Sana'a",
    "Sanaa",
    "Aden",
    "Taiz",
    "Hodeidah",
    "Mukalla",
    "Ibb",
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El-Kheima",
    "Port Said",
    "Suez",
    "Luxor",
    "Aswan",
    "Mansoura",
    "Tanta",
    "Asyut",
    "Ismailia",
    "Fayoum",
    "Zagazig",
    "Damietta",
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Djelfa",
    "Sétif",
    "Setif",
    "Sidi Bel Abbès",
    "Biskra",
    "Tébessa",
    "Tlemcen",
    "Béjaïa",
    "Tiaret",
    "Ouargla",
    "Skikda",
    "Tunis",
    "Sfax",
    "Sousse",
    "Kairouan",
    "Bizerte",
    "Gabès",
    "Ariana",
    "Gafsa",
    "Monastir",
    "Médenine",
    "Tripoli",
    "Benghazi",
    "Misrata",
    "Bayda",
    "Zawiya",
    "Tobruk",
    "Sabha",
    "Sirte",
    "Casablanca",
    "Rabat",
    "Fez",
    "Marrakesh",
    "Marrakech",
    "Tangier",
    "Salé",
    "Meknes",
    "Oujda",
    "Kenitra",
    "Tetouan",
    "Safi",
    "Agadir",
    "Mohammedia",
    "Khouribga",
    "El Jadida",
    "Nouakchott",
    "Nouadhibou",
    "Khartoum",
    "Omdurman",
    "Port Sudan",
    "Kassala",
    "Wad Medani",
    "El Obeid",
    "Juba",
    // ---- Sub-Saharan Africa ----
    "Lagos",
    "Kano",
    "Ibadan",
    "Abuja",
    "Port Harcourt",
    "Benin City",
    "Kaduna",
    "Maiduguri",
    "Zaria",
    "Aba",
    "Jos",
    "Ilorin",
    "Oyo",
    "Enugu",
    "Abeokuta",
    "Onitsha",
    "Warri",
    "Sokoto",
    "Calabar",
    "Uyo",
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Sunyani",
    "Cape Coast",
    "Tema",
    "Obuasi",
    "Abidjan",
    "Bouaké",
    "Bouake",
    "Daloa",
    "Yamoussoukro",
    "Korhogo",
    "San-Pédro",
    "Dakar",
    "Pikine",
    "Touba",
    "Thiès",
    "Thies",
    "Saint-Louis",
    "Kaolack",
    "Bamako",
    "Sikasso",
    "Mopti",
    "Koutiala",
    "Ségou",
    "Segou",
    "Kayes",
    "Ouagadougou",
    "Bobo-Dioulasso",
    "Koudougou",
    "Banfora",
    "Ouahigouya",
    "Niamey",
    "Zinder",
    "Maradi",
    "Agadez",
    "Tahoua",
    "Conakry",
    "Nzérékoré",
    "Kankan",
    "Boké",
    "Kindia",
    "Freetown",
    "Bo",
    "Kenema",
    "Makeni",
    "Koidu",
    "Monrovia",
    "Gbarnga",
    "Buchanan",
    "Yaoundé",
    "Douala",
    "Garoua",
    "Bafoussam",
    "Bamenda",
    "Maroua",
    "Ngaoundéré",
    "Bertoua",
    "Libreville",
    "Port-Gentil",
    "Franceville",
    "Brazzaville",
    "Pointe-Noire",
    "Dolisie",
    "Kinshasa",
    "Lubumbashi",
    "Mbuji-Mayi",
    "Kananga",
    "Kisangani",
    "Bukavu",
    "Tshikapa",
    "Goma",
    "Likasi",
    "Kolwezi",
    "Mbandaka",
    "Matadi",
    "Bangui",
    "Bimbo",
    "Berbérati",
    "N'Djamena",
    "Moundou",
    "Sarh",
    "Abéché",
    "Luanda",
    "Cabinda",
    "Huambo",
    "Lobito",
    "Benguela",
    "Lubango",
    "Malanje",
    "Namibe",
    "Nairobi",
    "Mombasa",
    "Nakuru",
    "Eldoret",
    "Kisumu",
    "Thika",
    "Ruiru",
    "Kikuyu",
    "Malindi",
    "Kakamega",
    "Naivasha",
    "Machakos",
    "Garissa",
    "Kampala",
    "Gulu",
    "Lira",
    "Mbarara",
    "Jinja",
    "Mbale",
    "Mukono",
    "Kasese",
    "Dar es Salaam",
    "Dodoma",
    "Mwanza",
    "Arusha",
    "Mbeya",
    "Morogoro",
    "Tanga",
    "Kahama",
    "Tabora",
    "Zanzibar",
    "Kigali",
    "Butare",
    "Gitarama",
    "Musanze",
    "Gisenyi",
    "Bujumbura",
    "Gitega",
    "Muyinga",
    "Ngozi",
    "Rumonge",
    "Addis Ababa",
    "Dire Dawa",
    "Mekele",
    "Gondar",
    "Adama",
    "Hawassa",
    "Bahir Dar",
    "Dessie",
    "Jimma",
    "Asmara",
    "Keren",
    "Massawa",
    "Mogadishu",
    "Hargeisa",
    "Bosaso",
    "Kismayo",
    "Berbera",
    "Djibouti City",
    "Ali Sabieh",
    "Tadjoura",
    "Lusaka",
    "Kitwe",
    "Ndola",
    "Kabwe",
    "Chingola",
    "Mufulira",
    "Livingstone",
    "Harare",
    "Bulawayo",
    "Chitungwiza",
    "Mutare",
    "Gweru",
    "Kwekwe",
    "Maputo",
    "Matola",
    "Beira",
    "Nampula",
    "Chimoio",
    "Quelimane",
    "Tete",
    "Antananarivo",
    "Toamasina",
    "Antsirabe",
    "Mahajanga",
    "Fianarantsoa",
    "Toliara",
    "Lilongwe",
    "Blantyre",
    "Mzuzu",
    "Zomba",
    "Kasungu",
    "Windhoek",
    "Walvis Bay",
    "Swakopmund",
    "Oshakati",
    "Rundu",
    "Gaborone",
    "Francistown",
    "Maun",
    "Molepolole",
    "Mahalapye",
    "Maseru",
    "Teyateyaneng",
    "Mafeteng",
    "Hlotse",
    "Mbabane",
    "Manzini",
    "Lobamba",
    "Cape Town",
    "Johannesburg",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
    "Soweto",
    "Bloemfontein",
    "Benoni",
    "Tembisa",
    "East London",
    "Vereeniging",
    "Boksburg",
    "Welkom",
    "Newcastle",
    "Krugersdorp",
    "Pietermaritzburg",
    "Roodepoort",
    "Botshabelo",
    "Brakpan",
    "Witbank",
    "Polokwane",
    "Mthatha",
    "Rustenburg",
    "Stellenbosch",
    "George",
    "Mossel Bay",
    "Knysna",
    // ---- Asia (East) ----
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Kitakyushu",
    "Chiba",
    "Sakai",
    "Niigata",
    "Hamamatsu",
    "Kumamoto",
    "Sagamihara",
    "Shizuoka",
    "Okayama",
    "Funabashi",
    "Kagoshima",
    "Hachiōji",
    "Hachioji",
    "Kawaguchi",
    "Himeji",
    "Suginami",
    "Matsuyama",
    "Higashiōsaka",
    "Nishinomiya",
    "Kurashiki",
    "Ichikawa",
    "Fukuyama",
    "Amagasaki",
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chongqing",
    "Tianjin",
    "Wuhan",
    "Dongguan",
    "Chengdu",
    "Foshan",
    "Nanjing",
    "Shenyang",
    "Hangzhou",
    "Xi'an",
    "Xian",
    "Harbin",
    "Suzhou",
    "Qingdao",
    "Dalian",
    "Zhengzhou",
    "Jinan",
    "Changsha",
    "Kunming",
    "Changchun",
    "Ürümqi",
    "Urumqi",
    "Shijiazhuang",
    "Taiyuan",
    "Hefei",
    "Nanchang",
    "Ningbo",
    "Wuxi",
    "Fuzhou",
    "Xiamen",
    "Lanzhou",
    "Guiyang",
    "Hohhot",
    "Nanning",
    "Tangshan",
    "Yantai",
    "Linyi",
    "Wenzhou",
    "Tianshui",
    "Changzhou",
    "Quanzhou",
    "Handan",
    "Baoding",
    "Zibo",
    "Shantou",
    "Datong",
    "Anshan",
    "Hong Kong",
    "Kowloon",
    "Macau",
    "Macao",
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Changwon",
    "Goyang",
    "Yongin",
    "Seongnam",
    "Bucheon",
    "Cheongju",
    "Ansan",
    "Anyang",
    "Jeonju",
    "Cheonan",
    "Pohang",
    "Jeju",
    "Pyongyang",
    "Hamhung",
    "Chongjin",
    "Nampo",
    "Wonsan",
    "Sinuiju",
    "Kaesong",
    "Taipei",
    "Kaohsiung",
    "Taichung",
    "Tainan",
    "Banqiao",
    "Taoyuan",
    "Hsinchu",
    "Keelung",
    "Chiayi",
    "Ulaanbaatar",
    "Erdenet",
    "Darkhan",
    "Choibalsan",
    "Mörön",
    // ---- Asia (Southeast) ----
    "Bangkok",
    "Samut Prakan",
    "Nonthaburi",
    "Udon Thani",
    "Chiang Mai",
    "Hat Yai",
    "Pak Kret",
    "Si Racha",
    "Khon Kaen",
    "Nakhon Ratchasima",
    "Chiang Rai",
    "Surat Thani",
    "Phuket",
    "Pattaya",
    "Hanoi",
    "Ho Chi Minh City",
    "Saigon",
    "Hai Phong",
    "Da Nang",
    "Can Tho",
    "Bien Hoa",
    "Hue",
    "Nha Trang",
    "Buon Ma Thuot",
    "Vung Tau",
    "Quy Nhon",
    "Long Xuyen",
    "Phan Thiet",
    "My Tho",
    "Ca Mau",
    "Phnom Penh",
    "Battambang",
    "Siem Reap",
    "Sihanoukville",
    "Poipet",
    "Ta Khmau",
    "Kampong Cham",
    "Vientiane",
    "Pakse",
    "Savannakhet",
    "Luang Prabang",
    "Thakhek",
    "Yangon",
    "Mandalay",
    "Naypyidaw",
    "Mawlamyine",
    "Bago",
    "Pathein",
    "Monywa",
    "Sittwe",
    "Manila",
    "Quezon City",
    "Caloocan",
    "Davao",
    "Cebu City",
    "Zamboanga",
    "Antipolo",
    "Pasig",
    "Cagayan de Oro",
    "Taguig",
    "Parañaque",
    "Dasmariñas",
    "Valenzuela",
    "Bacoor",
    "General Santos",
    "Las Piñas",
    "Makati",
    "Bacolod",
    "Iloilo City",
    "Mandaluyong",
    "Calamba",
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Bekasi",
    "Medan",
    "Tangerang",
    "Depok",
    "Semarang",
    "Palembang",
    "Makassar",
    "South Tangerang",
    "Batam",
    "Bogor",
    "Pekanbaru",
    "Bandar Lampung",
    "Padang",
    "Malang",
    "Denpasar",
    "Samarinda",
    "Yogyakarta",
    "Banjarmasin",
    "Tasikmalaya",
    "Pontianak",
    "Cimahi",
    "Balikpapan",
    "Jambi",
    "Surakarta",
    "Manado",
    "Cilegon",
    "Bali",
    "Lombok",
    "Kuala Lumpur",
    "George Town",
    "Ipoh",
    "Shah Alam",
    "Petaling Jaya",
    "Klang",
    "Johor Bahru",
    "Subang Jaya",
    "Kota Kinabalu",
    "Kuching",
    "Seremban",
    "Kuantan",
    "Alor Setar",
    "Miri",
    "Kota Bharu",
    "Sandakan",
    "Malacca",
    "Singapore",
    "Bandar Seri Begawan",
    "Kuala Belait",
    "Seria",
    "Tutong",
    "Dili",
    "Baucau",
    // ---- Asia (South) ----
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Bengaluru",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    "Navi Mumbai",
    "Allahabad",
    "Prayagraj",
    "Ranchi",
    "Howrah",
    "Coimbatore",
    "Jabalpur",
    "Gwalior",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Guwahati",
    "Chandigarh",
    "Solapur",
    "Hubli-Dharwad",
    "Mysore",
    "Tiruchirappalli",
    "Bareilly",
    "Aligarh",
    "Tiruppur",
    "Gurgaon",
    "Gurugram",
    "Noida",
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Gujranwala",
    "Peshawar",
    "Multan",
    "Hyderabad",
    "Islamabad",
    "Quetta",
    "Bahawalpur",
    "Sargodha",
    "Sialkot",
    "Sukkur",
    "Larkana",
    "Sheikhupura",
    "Mardan",
    "Gujrat",
    "Kasur",
    "Rahim Yar Khan",
    "Sahiwal",
    "Okara",
    "Wah Cantonment",
    "Dera Ghazi Khan",
    "Mingora",
    "Mirpur Khas",
    "Chiniot",
    "Dhaka",
    "Chittagong",
    "Khulna",
    "Rajshahi",
    "Sylhet",
    "Mymensingh",
    "Rangpur",
    "Comilla",
    "Narayanganj",
    "Gazipur",
    "Bogra",
    "Barisal",
    "Jessore",
    "Kabul",
    "Kandahar",
    "Herat",
    "Mazar-i-Sharif",
    "Jalalabad",
    "Kunduz",
    "Ghazni",
    "Lashkar Gah",
    "Taloqan",
    "Pul-e-Khumri",
    "Colombo",
    "Dehiwala-Mount Lavinia",
    "Moratuwa",
    "Sri Jayawardenepura Kotte",
    "Negombo",
    "Kandy",
    "Galle",
    "Jaffna",
    "Trincomalee",
    "Batticaloa",
    "Kathmandu",
    "Pokhara",
    "Lalitpur",
    "Bhaktapur",
    "Biratnagar",
    "Birgunj",
    "Dharan",
    "Janakpur",
    "Thimphu",
    "Phuntsholing",
    "Punakha",
    "Paro",
    "Wangdue Phodrang",
    "Malé",
    "Male",
    "Hithadhoo",
    "Fuvahmulah",
    "Kulhudhuffushi",
    // ---- Asia (Central) ----
    "Tashkent",
    "Samarkand",
    "Namangan",
    "Andijan",
    "Bukhara",
    "Nukus",
    "Qarshi",
    "Margilan",
    "Almaty",
    "Astana",
    "Nur-Sultan",
    "Shymkent",
    "Karaganda",
    "Aktobe",
    "Taraz",
    "Pavlodar",
    "Ust-Kamenogorsk",
    "Oskemen",
    "Semey",
    "Atyrau",
    "Kostanay",
    "Bishkek",
    "Osh",
    "Jalal-Abad",
    "Karakol",
    "Tokmok",
    "Dushanbe",
    "Khujand",
    "Kulob",
    "Qurghonteppa",
    "Istaravshan",
    "Ashgabat",
    "Türkmenabat",
    "Daşoguz",
    "Mary",
    "Türkmenbaşy",
    "Baku",
    "Ganja",
    "Sumqayit",
    "Mingachevir",
    "Şirvan",
    "Yerevan",
    "Gyumri",
    "Vanadzor",
    "Vagharshapat",
    "Ararat",
    "Tbilisi",
    "Kutaisi",
    "Batumi",
    "Rustavi",
    "Zugdidi",
    "Gori",
    // ---- Oceania ----
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Newcastle",
    "Wollongong",
    "Geelong",
    "Hobart",
    "Townsville",
    "Cairns",
    "Darwin",
    "Toowoomba",
    "Ballarat",
    "Bendigo",
    "Albury",
    "Launceston",
    "Mackay",
    "Rockhampton",
    "Bunbury",
    "Coffs Harbour",
    "Bundaberg",
    "Wagga Wagga",
    "Hervey Bay",
    "Mildura",
    "Shepparton",
    "Port Macquarie",
    "Gladstone",
    "Tamworth",
    "Traralgon",
    "Orange",
    "Geraldton",
    "Dubbo",
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Napier-Hastings",
    "Dunedin",
    "Palmerston North",
    "Nelson",
    "Rotorua",
    "New Plymouth",
    "Whangarei",
    "Invercargill",
    "Whanganui",
    "Gisborne",
    "Port Moresby",
    "Lae",
    "Madang",
    "Mount Hagen",
    "Goroka",
    "Wewak",
    "Suva",
    "Lautoka",
    "Nadi",
    "Labasa",
    "Ba",
    "Honiara",
    "Auki",
    "Gizo",
    "Buala",
    "Port Vila",
    "Luganville",
    "Norsup",
    "Sola",
    "Apia",
    "Salelologa",
    "Mulifanua",
    "Nuku'alofa",
    "Neiafu",
    "Tarawa",
    "Betio",
    "Bairiki",
    "Funafuti",
    "Asau",
    "Hagåtña",
    "Pago Pago",
    "Avarua",
    "Alofi",
    "Adamstown",
    "Yaren",
    "Ngerulmud",
    "Majuro",
    "Palikir",
    "Weno",
    "Kolonia",
];

// ============================================================================
// Ambiguous Place Names
// ============================================================================

/// Place names that are also common English words.
///
/// Matches against these entries are downgraded to `Low` confidence when
/// no location-context keyword appears in the surrounding text. The list
/// is intentionally small and conservative — it covers the highest-traffic
/// collisions where a free-text match without context is more likely to
/// be the English word than the place name.
///
/// Note: matches against `AMBIGUOUS_PLACE_NAMES` are NOT removed from the
/// gazetteer. The caller still receives an `IdentifierMatch` so audit
/// trails see the candidate; the consumer decides whether to redact based
/// on confidence.
pub(crate) const AMBIGUOUS_PLACE_NAMES: &[&str] = &[
    "Reading",      // UK city + common English verb
    "Mobile",       // Alabama city + adjective
    "Worth",        // Fort Worth shorthand + preposition/noun
    "Salem",        // Multiple US cities + biblical reference
    "Lima",         // Peru capital + Lima (US/Ohio) + bean
    "Bend",         // Oregon city + verb
    "Nice",         // French city + common adjective
    "Of",           // appears in many "City of X"; should not match alone
    "As",           // not a city alone
    "In",           // not a city alone
    "Or",           // not a city alone
    "To",           // not a city alone
    "He",           // not a city alone
    "Us",           // not a city alone
    "Independence", // US cities + abstract noun
    "Springfield",  // very common US city name + generic noun
    "Cambridge",    // UK/MA city + brand/proper noun usage
    "Oxford",       // UK city + brand/proper noun usage
    "Rochester",    // multiple US cities + brand usage
    "Manchester",   // UK/NH city + brand usage
    "Lancaster",    // multiple cities + brand usage
    "Madison",      // city + common name
    "Jackson",      // city + common name
    "York",         // UK city — collides with "New York"; checked separately
    "Concord",      // multiple cities + common noun
    "Aurora",       // multiple cities + common noun
    "Columbia",     // multiple cities + common noun
];
